### ISSUE TITLE
调到最大音量，但是声音还是很小

### ISSUE THREAD

**Issue by yuxunyang** [daliansky/Z370-Hackintosh#6]
直接拉过来的EFI，声音有，但是把音量调到最大，声音还是非常小。大佬是怎么解决的，可以分享一下不？

**Comment by daliansky** [comment]
一直以来，都是通过显示器上的`HDMI Audio`来输出声音的，所以真没太注意

**Comment by yuxunyang** [comment]
后面我用USB转Audio的转换器，声音就正常了
